/*
 * sonarlint4netbeans: SonarLint integration for Apache Netbeans
 * Copyright (C) 2020 Philippe FICHET.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 */
package com.github.philippefichet.sonarlint4netbeans;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.Collection;
import java.util.Optional;
import javax.swing.DefaultListModel;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.ErrorManager;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Exceptions;
import org.openide.util.Lookup;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;
import org.sonarsource.sonarlint.core.client.api.common.RuleDetails;

/**
 * Top component which displays something.
 * @author FICHET Philippe &lt;philippe.fichet@laposte.net&gt;
 */
@ConvertAsProperties(
    dtd = "-//com.github.philippefichet.sonarlint4netbeans//SonarRuleDetails//EN",
    autostore = false
)
@TopComponent.Description(
    preferredID = "SonarRuleDetailsTopComponent",
    iconBase = "com/github/philippefichet/sonarlint4netbeans/resources/sonarlint.png",
    persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "output", openAtStartup = false)
@ActionID(category = "Window", id = "com.github.philippefichet.sonarlint4netbeans.SonarRuleDetailsTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
    displayName = "#CTL_SonarRuleDetailsAction",
    preferredID = "SonarRuleDetailsTopComponent"
)
@Messages({
    "CTL_SonarRuleDetailsAction=Sonar Rule Details",
    "CTL_SonarRuleDetailsTopComponent=Sonar Rule Details Window",
    "HINT_SonarRuleDetailsTopComponent=This is a Sonar Rule Details window"
})
public final class SonarRuleDetailsTopComponent extends TopComponent {

    public SonarRuleDetailsTopComponent() {
        initComponents();
        setName(Bundle.CTL_SonarRuleDetailsTopComponent());
        setToolTipText(Bundle.HINT_SonarRuleDetailsTopComponent());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sonarRuleKeyFilter = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        sonarLintRuleDetailsEditor = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        sonarLintAllRules = new javax.swing.JList<>();

        setLayout(new java.awt.BorderLayout());

        sonarRuleKeyFilter.setText(org.openide.util.NbBundle.getMessage(SonarRuleDetailsTopComponent.class, "SonarRuleDetailsTopComponent.sonarRuleKeyFilter.text")); // NOI18N
        sonarRuleKeyFilter.setToolTipText(org.openide.util.NbBundle.getMessage(SonarRuleDetailsTopComponent.class, "SonarRuleDetailsTopComponent.sonarRuleKeyFilter.toolTipText")); // NOI18N
        sonarRuleKeyFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sonarRuleKeyFilterKeyReleased(evt);
            }
        });
        add(sonarRuleKeyFilter, java.awt.BorderLayout.PAGE_START);

        sonarLintRuleDetailsEditor.setEditable(false);
        sonarLintRuleDetailsEditor.setContentType("text/html");
        jScrollPane1.setViewportView(sonarLintRuleDetailsEditor);
        if (Desktop.isDesktopSupported()) {
            sonarLintRuleDetailsEditor.addHyperlinkListener(new HyperlinkListener() {
                @Override
                public void hyperlinkUpdate(HyperlinkEvent e) {
                    if (e.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
                        try {
                            Desktop.getDesktop().browse(e.getURL().toURI());
                        } catch (URISyntaxException | IOException ex) {
                            ErrorManager.getDefault().log("Unable to open browser on URL: " + e.getURL());
                            Exceptions.printStackTrace(ex);
                        }
                    }
                }
            });
        }

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        initListAllRuleDetailsRenderer();
        initListAllRuleDetails();
        sonarLintAllRules.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        sonarLintAllRules.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                sonarLintAllRulesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(sonarLintAllRules);

        add(jScrollPane2, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void sonarRuleKeyFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sonarRuleKeyFilterKeyReleased
        ruleKeyFilter = sonarRuleKeyFilter.getText().toLowerCase();
        initListAllRuleDetails();
    }//GEN-LAST:event_sonarRuleKeyFilterKeyReleased

    private void sonarLintAllRulesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_sonarLintAllRulesValueChanged
        String selectedValue = sonarLintAllRules.getSelectedValue();
        SonarLintEngine sonarLintEngine = Lookup.getDefault().lookup(SonarLintEngine.class);
        sonarLintEngine.whenInitialized((SonarLintEngine engine) -> {
            Optional<RuleDetails> optionalRuleDetails = engine.getRuleDetails(selectedValue);
            if (optionalRuleDetails.isPresent()) {
                RuleDetails ruleDetails = optionalRuleDetails.get();
                sonarLintRuleDetailsEditor.setText(
                    "<h1><a href=\"" + SonarLintUtils.toURL(ruleDetails) + "\">" + ruleDetails.getName() + "</a></h1>"
                    + ruleDetails.getHtmlDescription()
                );
                sonarLintRuleDetailsEditor.getCaret().moveDot(0);
            }
        });
    }//GEN-LAST:event_sonarLintAllRulesValueChanged

    private void initListAllRuleDetailsRenderer()
    {
        SonarLintEngine sonarLintEngine = Lookup.getDefault().lookup(SonarLintEngine.class);
        sonarLintEngine.whenConfigurationChanged(engine -> sonarLintAllRules.repaint());
        sonarLintAllRules.setCellRenderer(new SonarLintListCellRenderer(sonarLintEngine));
        sonarLintAllRules.addMouseListener(new SonarLintListMouseAdapter(sonarLintAllRules, sonarLintEngine));
    }
    
    private void initListAllRuleDetails() {
        SonarLintEngine sonarLintEngine = Lookup.getDefault().lookup(SonarLintEngine.class);
        sonarLintEngine.whenInitialized((SonarLintEngine engine) -> {
            DefaultListModel<String> model = new DefaultListModel<>();
            Collection<RuleDetails> rules = engine.getAllRuleDetails();
            rules.stream().sorted((r1, r2) -> r1.getKey().compareTo(r2.getKey()))
            .filter(SonarLintUtils.FilterBy.keyAndName(ruleKeyFilter))
            .forEach(rule -> model.addElement(rule.getKey()));
            sonarLintAllRules.setModel(model);
            sonarLintAllRules.updateUI();
        });
    }

    private String ruleKeyFilter = "";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> sonarLintAllRules;
    private javax.swing.JEditorPane sonarLintRuleDetailsEditor;
    private javax.swing.JTextField sonarRuleKeyFilter;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    
    public void setSonarRuleKeyFilter(String sonarRuleKeyFilter)
    {
        this.sonarRuleKeyFilter.setText(sonarRuleKeyFilter);
        ruleKeyFilter = this.sonarRuleKeyFilter.getText().toLowerCase();
        initListAllRuleDetails();
        sonarLintAllRules.setSelectedValue(sonarRuleKeyFilter, true);
        updateUI();
    }
}
