/*
 * sonarlint4netbeans: SonarLint integration for Apache Netbeans
 * Copyright (C) 2020 Philippe FICHET.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 */
package com.github.philippefichet.sonarlint4netbeans.project.ui;

import com.github.philippefichet.sonarlint4netbeans.SonarLintDataManager;
import com.github.philippefichet.sonarlint4netbeans.project.SonarLintProjectPreferenceScope;
import java.awt.event.ActionEvent;
import org.netbeans.api.project.Project;
import org.netbeans.spi.project.ui.support.ProjectCustomizer;

/**
 * Panel to choose project scope for rule settings
 * @author FICHET Philippe &lt;philippe.fichet@laposte.net&gt;
 */
public class SonarLintProjectCustomizerPanel extends javax.swing.JPanel {
    private SonarLintProjectPreferenceScope scope = SonarLintProjectPreferenceScope.GLOBAL;

    /**
     * Creates new form SonarLintProjectCustomizerPanel
     */
    public SonarLintProjectCustomizerPanel(SonarLintDataManager sonarLintDataManager, Project project, ProjectCustomizer.Category category) {
        initComponents();
        SonarLintProjectPreferenceScope actualScope = sonarLintDataManager.getPreferencesScope(project);
        if (actualScope == SonarLintProjectPreferenceScope.PROJECT) {
            scopeProjectRadioButton.setSelected(true);
        }
        category.setOkButtonListener((ActionEvent actionEvent) ->
            sonarLintDataManager.setPreferencesScope(project, scope)
        );
        scopeGlobalRadioButton.addActionListener((ActionEvent actionEvent) ->
            scope = SonarLintProjectPreferenceScope.GLOBAL
        );
        scopeProjectRadioButton.addActionListener((ActionEvent actionEvent) ->
            scope = SonarLintProjectPreferenceScope.PROJECT
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scopeRadioButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        scopeGlobalRadioButton = new javax.swing.JRadioButton();
        scopeProjectRadioButton = new javax.swing.JRadioButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        scopeRadioButtonGroup.add(scopeGlobalRadioButton);
        scopeGlobalRadioButton.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(scopeGlobalRadioButton, org.openide.util.NbBundle.getMessage(SonarLintProjectCustomizerPanel.class, "SonarLintProjectCustomizerPanel.scopeGlobalRadioButton.text")); // NOI18N
        jPanel1.add(scopeGlobalRadioButton);

        scopeRadioButtonGroup.add(scopeProjectRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(scopeProjectRadioButton, org.openide.util.NbBundle.getMessage(SonarLintProjectCustomizerPanel.class, "SonarLintProjectCustomizerPanel.scopeProjectRadioButton.text")); // NOI18N
        jPanel1.add(scopeProjectRadioButton);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton scopeGlobalRadioButton;
    private javax.swing.JRadioButton scopeProjectRadioButton;
    private javax.swing.ButtonGroup scopeRadioButtonGroup;
    // End of variables declaration//GEN-END:variables
}
